### ISSUE TITLE
Setup code coverage with Coveralls

### ISSUE THREAD

**Issue by YukieK** [YukieK/GeekHours#13]
Setup code coverage and add badge to README.md.

Coveralls
https://coveralls.io/

**Comment by YukieK** [comment]
`coveralls` command fails when running on CircleCi.
https://circleci.com/gh/YukieK/GeekHours/129

Pending this issue because no solution found.

**Comment by mitsutaka** [comment]
Solved by https://github.com/YukieK/GeekHours/pull/17
